# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['*']
#         # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/': null

# nelmio_cors:
#     defaults:
#         allow_credentials: true
#         allow_origin: ['*']
#         allow_headers: ['Content-Type', 'Authorization']
#         allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
#         expose_headers: ['Link']
#         max_age: 3600
# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_credentials: true
#         allow_origin: ['*']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 42000
#     paths:
#         '^/': null

# app/config/config.yml

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'GET', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
